/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RestaurantMenuItem {
        "imageUrl": string;
        "name": string;
        "price": number;
    }
}
declare global {
    interface HTMLRestaurantMenuItemElement extends Components.RestaurantMenuItem, HTMLStencilElement {
    }
    var HTMLRestaurantMenuItemElement: {
        prototype: HTMLRestaurantMenuItemElement;
        new (): HTMLRestaurantMenuItemElement;
    };
    interface HTMLElementTagNameMap {
        "restaurant-menu-item": HTMLRestaurantMenuItemElement;
    }
}
declare namespace LocalJSX {
    interface RestaurantMenuItem {
        "imageUrl"?: string;
        "name"?: string;
        "price"?: number;
    }
    interface IntrinsicElements {
        "restaurant-menu-item": RestaurantMenuItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "restaurant-menu-item": LocalJSX.RestaurantMenuItem & JSXBase.HTMLAttributes<HTMLRestaurantMenuItemElement>;
        }
    }
}
